spring.application.name=leafon-api

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?user=postgres.cieqfhwerpxomfvelojq&password=@VilaDaFolha
spring.datasource.username=postgres.cieqfhwerpxomfvelojq
spring.datasource.password=${SUPABASE_DATABASE_PASSWORD:}
spring.datasource.driverClassName=org.postgresql.Driver

leafon.security.supabase.jwt.issuer-uri=https://cieqfhwerpxomfvelojq.supabase.co/auth/v1
leafon.security.supabase.jwt.jwk-set-uri=https://cieqfhwerpxomfvelojq.supabase.co/auth/v1/.well-known/jwks.json
leafon.security.supabase.jwt.audience=authenticated
leafon.supabase.admin.project-url=https://cieqfhwerpxomfvelojq.supabase.co
leafon.supabase.admin.service-role-key=test-service-role-key
leafon.supabase.admin.email-confirm=true
