spring.application.name=leafon-api

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?user=postgres.cieqfhwerpxomfvelojq&password=@VilaDaFolha
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_DATABASE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver





#